name: point_of_sale_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.0
  http: ^1.2.2
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  socket_io_client: ^3.0.2
  win32: ^5.5.0 # Versión ajustada para compatibilidad
  pdf: ^3.11.1
  flutter_pdfview: ^1.3.4
  google_fonts: ^6.2.1
  file_picker: ^8.1.6
  pdf_image_renderer: ^0.7.0
  csv: ^6.0.0
  printing: ^5.14.2
  syncfusion_flutter_charts: ^25.2.7
  excel: ^4.0.6
  open_file: ^3.5.10
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11 # Versión ajustada para compatibilidad
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg # Corregido a minúscula
