# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # O una versión más reciente

      # Obtiene las dependencias de Flutter.
      - run: flutter pub get

      # Revisa si hay problemas de formato en el código.
      - run: flutter analyze

      # Ejecuta las pruebas de widgets para nuestro proyecto de Flutter.
      - run: flutter test

      - run: flutter build apk
      - run: flutter build appbundle
